[tool.poetry]
name = "bak-translation-tools"
version = "0.1.0"
description = ""
authors = ["Andrey Fedoseev <andrey@andreyfedoseev.com>"]

[tool.poetry.dependencies]
python = "^3.10"
filebuffer = { path = "./lib/filebuffer", develop = true }
bitstring = "^3.1.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
