[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bak-translation-tools"
requires-python = ">=3.9"
version = "0.1.0"
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Typing :: Typed",
]
description = ""
dependencies = [
    "bitstring==3.1.9",
    "Pillow==9.2.0",
]

[tool.setuptools.packages.find]
where = ["src"]
